FROM python:3.9-slim
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0

# Copier le fichier local dans le conteneur
COPY * .
COPY neural_de ./neural_de
RUN python -m pip install .

ADD neural_de/main.py .

ENTRYPOINT python main.py \
    --input_source_path "/tmp/in"/"$INPUT_SOURCE_PATH" \
    --output_target_path "/tmp/out"/"$OUTPUT_TARGET_PATH" \
    --output_prefix "$OUTPUT_PREFIX" \
    --pipeline_file_path "/tmp"/"$PIPELINE_FILE_PATH"

